using CryptoExchange.Net.Objects;
using HyperLiquid.Net.Objects.Internal;
using HyperLiquid.Net.Objects.Models;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HyperLiquid.Net.Converters
{
    [JsonSerializable(typeof(Dictionary<string, decimal>))]
    [JsonSerializable(typeof(List<ParameterCollection>))]
    [JsonSerializable(typeof(HyperLiquidResponse<HyperLiquidOrderResultIntWrapper>))]
    [JsonSerializable(typeof(HyperLiquidResponse<HyperLiquidCancelResult>))]
    [JsonSerializable(typeof(HyperLiquidResponse<HyperLiquidTwapOrderResultIntWrapper>))]
    [JsonSerializable(typeof(HyperLiquidResponse<HyperLiquidTwapCancelResult>))]
    [JsonSerializable(typeof(CancelResultConverter.ErrorMessage))]
    [JsonSerializable(typeof(HyperLiquidResponse<HyperLiquidDefault>))]

    // End manual defined attributes

    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidTrade[]>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidOrderStatus[]>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidUserFunding[]>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidDeposit[]>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidWithdrawal[]>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidInternalTransfer[]>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidLiquidation[]>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidSpotTransfer[]>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSubscribeRequest>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidMidsUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidKline>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidOrderBook>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidLedgerUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidUserUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidUserTradeUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidTwapTradeUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidTwapOrderUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidFuturesTickerUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidFuturesUserSymbolUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidUserFundingUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidTickerUpdate>))]
    [JsonSerializable(typeof(IDictionary<string, object>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidDeposit>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidWithdrawal>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidInternalTransfer>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidLiquidation>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidSpotTransfer>))]
    [JsonSerializable(typeof(HyperLiquidUserTrade[]))]
    [JsonSerializable(typeof(HyperLiquidTwapStatus[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderStatus[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderUpdate[]))]
    [JsonSerializable(typeof(HyperLiquidTwapTradeUpdate[]))]
    [JsonSerializable(typeof(HyperLiquidAccountLedger[]))]
    [JsonSerializable(typeof(HyperLiquidLiquidationPosition[]))]
    [JsonSerializable(typeof(HyperLiquidAssetInfo[]))]
    [JsonSerializable(typeof(HyperLiquidAssetGenesis[]))]
    [JsonSerializable(typeof(AddressBalance[]))]
    [JsonSerializable(typeof(AddressIndexBalance[]))]
    [JsonSerializable(typeof(HyperLiquidBalances[]))]
    [JsonSerializable(typeof(HyperLiquidBalance[]))]
    [JsonSerializable(typeof(HyperLiquidCancelRequest[]))]
    [JsonSerializable(typeof(HyperLiquidCancelByClientOrderIdRequest[]))]
    [JsonSerializable(typeof(HyperLiquidCancelResult[]))]
    [JsonSerializable(typeof(HyperLiquidEditOrderRequest[]))]
    [JsonSerializable(typeof(HyperLiquidExchangeInfoAndTickers[]))]
    [JsonSerializable(typeof(HyperLiquidTicker[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfo[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfoVolume[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfoSchedule[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfoFeeTier[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfoFeeTierRate[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfoFeeTierRateMarketMaker[]))]
    [JsonSerializable(typeof(HyperLiquidFundingRate[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesAccount[]))]
    [JsonSerializable(typeof(HyperLiquidMarginSummary[]))]
    [JsonSerializable(typeof(HyperLiquidPosition[]))]
    [JsonSerializable(typeof(HyperLiquidPositionInfo[]))]
    [JsonSerializable(typeof(HyperLiquidPositionLeverage[]))]
    [JsonSerializable(typeof(HyperLiquidPositionFunding[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesExchangeInfo[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesSymbol[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesExchangeInfoAndTickers[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesTicker[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesUserSymbolUpdate[]))]
    [JsonSerializable(typeof(HyperLiquidLeverage[]))]
    [JsonSerializable(typeof(HyperLiquidKline[]))]
    [JsonSerializable(typeof(HyperLiquidOpenOrder[]))]
    [JsonSerializable(typeof(HyperLiquidOrder[]))]
    [JsonSerializable(typeof(HyperLiquidOrderBook[]))]
    [JsonSerializable(typeof(HyperLiquidOrderBookLevels[]))]
    [JsonSerializable(typeof(HyperLiquidOrderBookEntry[]))]
    [JsonSerializable(typeof(HyperLiquidOrderRequest[]))]
    [JsonSerializable(typeof(HyperLiquidOrderResultIntWrapper[]))]
    [JsonSerializable(typeof(HyperLiquidOrderResultInt[]))]
    [JsonSerializable(typeof(HyperLiquidOrderResult[]))]
    [JsonSerializable(typeof(HyperLiquidOrderStatusResult[]))]
    [JsonSerializable(typeof(HyperLiquidRateLimit[]))]
    [JsonSerializable(typeof(HyperLiquidSpotExchangeInfo[]))]
    [JsonSerializable(typeof(HyperLiquidSymbol[]))]
    [JsonSerializable(typeof(HyperLiquidAsset[]))]
    [JsonSerializable(typeof(HyperLiquidSymbolReference[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderResultIntWrapper[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderResultInt[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderResult[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderStatusDesc[]))]
    [JsonSerializable(typeof(HyperLiquidUserUpdate[]))]
    [JsonSerializable(typeof(HyperLiquidPong))]
    [JsonSerializable(typeof(HyperLiquidPing))]
    [JsonSerializable(typeof(HyperLiquidUnsubscribeRequest))]
    [JsonSerializable(typeof(HyperLiquidSocketRequest))]
    [JsonSerializable(typeof(string))]
    [JsonSerializable(typeof(int?))]
    [JsonSerializable(typeof(int))]
    [JsonSerializable(typeof(long?))]
    [JsonSerializable(typeof(long))]
    [JsonSerializable(typeof(decimal?))]
    [JsonSerializable(typeof(decimal))]
    [JsonSerializable(typeof(DateTime))]
    [JsonSerializable(typeof(DateTime?))]
    internal partial class HyperLiquidSourceGenerationContext : JsonSerializerContext
    {
    }
}
